name: Cypress Tests

on:
 workflow_dispatch:
   inputs:
     cli:
       description: Run by cypress command line
       default: yarn cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
      
      - name: Install dependencies
        run: yarn install
      
      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
        
      - name: Cypress report action duynhanf   
        uses: duynhanf/cypress-report-action@v13
