name: Cypress Tests

on: [push]

jobs:
 cypress-electron-tests:
   runs-on: ubuntu-latest
   steps:
    - name: Get code
      uses: actions/checkout@v3.5.2
      
    - name: Install dependencies
      run: npm install
      
    - name: Run E2E tests
      run: npm cypress run
